### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by averagehat** [dr-artio/ERIF#1]
``` bash
bash-4.1$ samtools view -h ../780/780.bam H3N2/CY074922/Managua/2010/PB2_1 > 780.sam
bash-4.1$ java -cp target/erif-1.1.jar:target/dependency/* edu.gsu.cs.align.exec.Main   780.sam -g ../780/780.ref.fasta
[10:41:04 AM] --------------------------------------------
[10:41:04 AM] ERIF v null Extended Reference Insertion Fixer
[10:41:04 AM] --------------------------------------------
[10:41:04 AM] Total reads:10143
[10:41:04 AM] Filtering...
[10:41:04 AM] Filtered reads:10143
[10:41:04 AM] Alignment started...
String index out of range: 250
java.lang.StringIndexOutOfBoundsException: String index out of range: 250
    at java.lang.String.substring(String.java:1907)
    at edu.gsu.cs.align.model.InsertionsAligner$$anonfun$buildAndInitInsertionsTable$2$$anonfun$apply$2.apply(InsertionsAligner.scala:88)
    at edu.gsu.cs.align.model.InsertionsAligner$$anonfun$buildAndInitInsertionsTable$2$$anonfun$apply$2.apply(InsertionsAligner.scala:86)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at edu.gsu.cs.align.model.InsertionsAligner$$anonfun$buildAndInitInsertionsTable$2.apply(InsertionsAligner.scala:86)
    at edu.gsu.cs.align.model.InsertionsAligner$$anonfun$buildAndInitInsertionsTable$2.apply(InsertionsAligner.scala:83)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at edu.gsu.cs.align.model.InsertionsAligner$.buildAndInitInsertionsTable(InsertionsAligner.scala:83)
    at edu.gsu.cs.align.exec.package$.performAlignment(package.scala:88)
    at edu.gsu.cs.align.exec.Main$.main(Main.scala:34)
    at edu.gsu.cs.align.exec.Main.main(Main.scala)
```

I can link the files if need be, but the other set of `sam` and reference fasta files I tried also gave the same error.

**Comment by dr-artio** [comment]
First of all my program designed to use single reference (it can take several but they should have approximately equal length). This exception is usually raised when multiple references with different lengths are present. This version of erif tuned for amplicon data as well as kGEM. You can though split reads mapped to different references and try to run it only on reads mapped to the same reference.
